# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=2000
SAVEHIST=2000
bindkey -e
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/jas/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall
###################################

# Autocorrect captilization on pressing tab
zstyle ':completion:*' matcher-list '' 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'

# Enable cd-ing without typing cd
setopt autocd

# Enables some modifier keybinds
source ~/.zshkeys

# Enables a few external apps
source ~/.apps

# Enables zsh powerline
powerline-daemon -q
. /usr/share/powerline/bindings/zsh/powerline.zsh

# zsh suggestion, syntax highlighter support and expand multiple dots support
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
source /usr/share/zsh/plugins/zsh-expand-dots/zsh-expand-dots.zsh

# fzf zsh integration
source /usr/share/fzf/key-bindings.zsh
source /usr/share/fzf/completion.zsh

# Use vim as the editor of choice
export VISUAL="vim"
export EDITOR="$VISUAL"

# Aliased list dir commands
alias ls=exa
alias ll="exa -lah"
alias l=exa

# Prevent accidental deletions by requiring confirmation
alias rm="rm -i"

# Makes less searches appear in the middleish of the screen rather than the top
export LESS="-R -j.45"

# Cool weather display
alias weather='curl wttr.in/${city}'
